### ISSUE TITLE
Basic Implementation of Personal Scheduler feature

### ISSUE THREAD

**Issue by gsyndromes** [AY1920S2-CS2103T-W12-2/main#40]
program scheduler that can view and sort according to time

**Comment by garysyndromes** [comment]
add an empty tab and route it properly such that it is accessable by the command
schedule

**Comment by garysyndromes** [comment]
be able to add and edit items (in text) in the schedule page that willl be sorted according to time

**Comment by garysyndromes** [comment]
fix up GUI for program scheduler

**Comment by jerrenss** [comment]
Hi Gary, just a gentle reminder to close this issue once the objectives are achieved. We can then move on to focus on intermediate level implementations. Cheers!
