### ISSUE TITLE
Basic Implementation of Class Progress Management feature 

### ISSUE THREAD

**Issue by jerrenss** [AY1920S2-CS2103T-W12-2/main#45]

**Comment by tingalinga** [comment]
- [x] Add Homework class (description, deadline, list of submissions)
- [x] Add Submission class (student, date of submission, status [late, on time])
- [x] Statistics of homework (average, highest, lowest)

**Comment by jerrenss** [comment]
Hi Huiting, just a gentle reminder to close this issue once the objectives are achieved. We can then move on to focus on intermediate level implementations. Cheers!
